---
title: "PCA_3d"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PCA_3d}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(glab.library2)
```

```{r}
data(iris)
iris.pca <- prcomp(iris[, -c(5)], center = TRUE, scale. = TRUE)
scores <- as.data.frame(iris.pca$x)
scores <- cbind(rownames(iris), scores)
names(scores)[1] <- "Score"
info <- cbind(rownames(iris), as.data.frame(iris[, "Species"]))
names(info)[1] <- "cellline"
names(info)[2] <- "Group"

plot_PCA_3d(scores = scores, 
            info = info, info.Group = info$Group, 
            grouplabels = TRUE, Title = "3D Plot-Iris Species", drawshape = TRUE)
plot_PCA_3d(scores = scores, 
            info = info, info.Group = info$Group, 
            grouplabels = TRUE, Title = "3D Plot-Iris Species")
plot_PCA_3d(scores = scores, 
            info = info, indiv_labels = TRUE, 
            Title = "3D Plot-Iris Species")
```

